/**
 * 所有功能通用属性
 */
export default class CommonConstants {
  /**
   * 账户输入长度
   */
  static readonly INPUT_ACCOUNT_LENGTH = 11

  /**
   * 密码输入长度
   */
  static readonly INPUT_PASSWORD_LENGTH = 8

  /**
   * 输入框左侧边距
   */
  static readonly INPUT_PADDING_LEFT = 0

  /**
   * 模拟登录耗时，单位毫秒
   */
  static readonly LOGIN_DELAY_TIME = 2000

  /**
   * 组件通用间距
   */
  static readonly COMMON_SPACE = 12

  /**
   * 登录方式间距
   */
  static readonly LOGIN_METHODS_SPACE = 44

  /**
   * 填充父布局的宽高尺寸
   */
  static readonly FULL_PARENT = '100%'

  /**
   * 按钮宽度
   */
  static readonly BUTTON_WIDTH = '90%'

  /**
   * 设置列表宽度
   */
  static readonly SET_LIST_WIDTH = '42%'

  /**
   * 首页Tab位置
   */
  static readonly HOME_TAB_INDEX = 0

  /**
   * 我的Tab位置
   */
  static readonly MINE_TAB_INDEX = 1
}